database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "yourpassword"
  dbname: "postgres"
  sslmode: "disable"

paths:
  xml_dumps_dir: "/path/to/xml/dumps"
  output_sql_file: "../filtered_schema.sql"
  schema_file: "../schema.sql"